"use client";

import { Theme } from "@components/theme";
import * as Icon from "@deemlol/next-icons";
import { useContext, useState } from "react";
import { motion } from "framer-motion";
import Subway from "@components/ui/subway";

export default function Header() {
  const [isMenu, setIsMenu] = useState<boolean>(false);

  const menuToggle = () => {
    setIsMenu(!isMenu);
  };

  const seoulDistricts = [
    "강남구",
    "강동구",
    "강북구",
    "강서구",
    "관악구",
    "광진구",
    "구로구",
    "금천구",
    "노원구",
    "도봉구",
    "동대문구",
    "동작구",
    "마포구",
    "서대문구",
    "서초구",
    "성동구",
    "성북구",
    "송파구",
    "양천구",
    "영등포구",
    "용산구",
    "은평구",
    "종로구",
    "중구",
    "중랑구",
  ];

  return (
    <>
      <header
        className="
          flex
          flex-row
          items-center
          justify-center
          w-full
          bg-white
          h-[60px]
          z-[1000]
          fixed
          top-0
          left-0
        "
      >
        <div
          className="
            flex
            flex-row
            items-center
            h-full
            justify-between
            w-[--layout]
            bg-[--white]
            z-[100]
          "
        >
          <p
            className="
              text-black
              z-[100]
            "
          >
            로고
          </p>
          <nav
            className="
              flex
              flex-row
              w-auto
              z-[100]
            "
          >
            <ul
              className="
                flex
                flex-row
                items-center
                justifet-center
              "
            >
              <li
                className="
                  text-[16px]
                  cursor-pointer
                  duration-500
                  hover:font-[700]
                  hover:text-[var(--main)]
                "
                onClick={menuToggle}
              >
                <a>지역여행</a>
              </li>

              <li
                className="
                  text-[16px]
                  cursor-pointer
                  mx-[10px]
                  duration-500
                  hover:font-[700]
                  hover:text-[var(--main)]
                "
              >
                <a>카테고리여행</a>
              </li>
              <li
                className="
                  flex
                  flex-col
                  items-center
                  justify-center
                  size-[30px]
                  rounded-[50px]
                  bg-[--main]
                "
              >
                <Icon.User size={16} color="#fff" />
              </li>
            </ul>
          </nav>
        </div>
      </header>

      <motion.div
        initial={{ top: `-550px` }}
        animate={{ top: isMenu ? `60px` : `-550px` }}
        className="
          flex
          flex-col
          items-center
          justify-center
          w-full
          shadow-md
          fixed
          top-0
          left-0
          h-[550px]
          bg-[--white]
          z-[100]
        "
      >
        <nav
          className="
            flex
            flex-col
            h-full
            w-[--layout]
          "
        >
          <ul
            className="
              flex
              flex-row
              items-center
              justify-center
              bg-[--lightGrey]
              h-[54px]
              rounded-[15px]
              p-[10px]
              relative
              mb-[10px]
            "
          >
            <li
              className="
                h-[calc(100%-20px)]
                absolute
                top-[10px]
                left-[10px]
                bg-[--white]
                w-[calc(25%-20px)]
                rounded-[10px]
                z-[1]
              "
            ></li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--black]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              서울특별시
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              인천광역시
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              경기도
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              강원도
            </li>
          </ul>
          <ul
            className="
              flex
              flex-row
              items-center
              justify-center
              bg-[--lightGrey]
              h-[54px]
              rounded-[15px]
              p-[10px]
              relative
              mb-[10px]
            "
          >
            <li
              className="
                h-[calc(100%-20px)]
                absolute
                top-[10px]
                left-[10px]
                w-[calc(25%-20px)]
                rounded-[10px]
                z-[1]
              "
            ></li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              충청북도
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              대전광역시
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              충청남도
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              경상북도
            </li>
          </ul>
          <ul
            className="
              flex
              flex-row
              items-center
              justify-center
              bg-[--lightGrey]
              h-[54px]
              rounded-[15px]
              p-[10px]
              relative
              mb-[10px]
            "
          >
            <li
              className="
                h-[calc(100%-20px)]
                absolute
                top-[10px]
                left-[10px]
                w-[calc(25%-20px)]
                rounded-[10px]
                z-[1]
              "
            ></li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              대구광역시
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              경상남도
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              부산광역시
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              울산광역시
            </li>
          </ul>
          <ul
            className="
              flex
              flex-row
              items-center
              justify-center
              bg-[--lightGrey]
              h-[54px]
              rounded-[15px]
              p-[10px]
              relative
              mb-[20px]
            "
          >
            <li
              className="
                h-[calc(100%-20px)]
                absolute
                top-[10px]
                left-[10px]
                w-[calc(25%-20px)]
                rounded-[10px]
                z-[1]
              "
            ></li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              전라북도
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              전라남도
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              광주광역시
            </li>
            <li
              className="
                flex
                flex-col
                items-center
                justify-center
                w-[25%]
                text-[--grey]
                text-[16px]
                font-[700]
                cursor-pointer
                z-[2]
              "
            >
              제주도
            </li>
          </ul>
          <div
            className="
              flex
              flex-col
              items-center
              justify-center
              w-full
              relative
              mb-[20px]
            "
          >
            <div
              className="
                absolute
                w-screen
                bg-[--main]
                h-[10px]
                z-[-1]
                inset-auto
              "
            />
            <Subway title={"서울특별시"} />
          </div>

          <ul
            className="
              flex
              flex-row
              items-center
              justify-start
              flex-wrap
            "
          >
            {seoulDistricts.map((data, idx) => {
              return (
                <button
                  key={idx}
                  className="
                    text-center
                    w-[120px]
                    h-[25px]
                    rounded-[20px]
                    border-[--lightGrey2]
                    border
                    text-[14px]
                    font-[700]
                    text-[--grey]
                    duration-500
                    mx-[5px]
                    mb-[5px]
                    hover:bg-[--grey]
                    hover:text-[--white]
                  "
                >
                  {data}
                </button>
              );
            })}
          </ul>
        </nav>
      </motion.div>
    </>
  );
}
