// Page.jsx (서버 컴포넌트)
import { Metadata } from "@node_modules/next";
import ClientPage from "./clientPage";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by Next.js",
};

export default function Page() {
  return <ClientPage />;
}
