export default function Subway(data: { title: string }) {
  return (
    <div
      className="
        flex
        flex-col
        items-center
        justify-center
        w-[180px]
        h-[40px]
        bg-[--main]
        p-[6px]
        rounded-[50px]
      "
    >
      <ul
        className="
          flex
          flex-row
          items-center
          justify-center
          size-full
          rounded-[50px]
          bg-[hsl(var(--background))]
          px-[10px]
        "
      >
        <li
          className="
            rounded-full
            bg-[--main]
            size-[20px]
          "
        ></li>
        <li
          className="
            text-center
            w-[calc(100%-20px)]
            text-[16px]
            font-[700]
          "
        >
          {data.title}
        </li>
      </ul>
    </div>
  );
}
